### ISSUE TITLE
How to estimate the poses of multiple objects simultaneously

### ISSUE THREAD

**Issue by qiqi7749** [Jiyao06/GenPose#23]
Hi,

I've noticed that GenPose can only estimate the pose of one object at a time. If I want to estimate the poses of multiple objects simultaneously, what should I do? Should I first segment the point cloud and then infer all segmented point clouds together? Will this approach be slow? Additionally, when inferring the target poses, do I need to segment the targets first, or is it possible to automatically detect the targets in complex environments?

Looking forward to your response.

**Comment by Jiyao06** [comment]
When aiming to predict poses for multiple objects simultaneously, it is recommended to employ a segmentation model to obtain masks for each object. Subsequently, predict the pose for each object independently. Since objects are mutually independent, this process can be parallelized, ensuring minimal impact on speed.

**Comment by qiqi7749** [comment]
> When aiming to predict poses for multiple objects simultaneously, it is recommended to employ a segmentation model to obtain masks for each object. Subsequently, predict the pose for each object independently. Since objects are mutually independent, this process can be parallelized, ensuring minimal impact on speed.

Thank you for your response. I have another question. For cylindrical objects, there should be an axis that always aligns with its axis direction, and ideally, the annotations of cylindrical objects in the dataset should be like this. However, when recognizing objects in practice, I found that the obtained object pose always has the y-axis pointing upward. What could be the reasons for this result?

![can_pose1](https://github.com/Jiyao06/GenPose/assets/140774285/108d64d0-8619-4b72-a9f9-975379812bdb)
![can_pose2](https://github.com/Jiyao06/GenPose/assets/140774285/18b432b6-8cf7-474f-a7dd-44446eca1b47)
![can_pose3](https://github.com/Jiyao06/GenPose/assets/140774285/a090418e-89ec-4a17-94a7-048c424b87c3)

**Comment by Jiyao06** [comment]
I think this is a good question, and I suspect that the objects in the CAMERA and REAL275 datasets are mostly in an upright orientation, leading to a training data bias. As a result, the model tends to recognize the object pose with the y-axis pointing upward in practice.

To address this issue, we can consider the following approaches:

1. **Data Augmentation**: Apply data augmentation techniques during training, such as random rotations and flips, to make the model more robust to different object orientations.

2. **Multi-Dataset Training**: Incorporate additional datasets beyond CAMERA and REAL275 for training to reduce the bias caused by a single dataset.

By implementing these strategies, we can improve the model's performance in recognizing and handling objects with various orientations in practical applications.

**Comment by qiqi7749** [comment]
> I think this is a good question, and I suspect that the objects in the CAMERA and REAL275 datasets are mostly in an upright orientation, leading to a training data bias. As a result, the model tends to recognize the object pose with the y-axis pointing upward in practice.
> 
> To address this issue, we can consider the following approaches:
> 
> 1. **Data Augmentation**: Apply data augmentation techniques during training, such as random rotations and flips, to make the model more robust to different object orientations.
> 2. **Multi-Dataset Training**: Incorporate additional datasets beyond CAMERA and REAL275 for training to reduce the bias caused by a single dataset.
> 
> By implementing these strategies, we can improve the model's performance in recognizing and handling objects with various orientations in practical applications.

Thanks a lot for your suggestion!
